### ISSUE TITLE
Bot went Berzerk on 11/10

### ISSUE THREAD

**Issue by grahams** [ErinMorelli/em-slack-french-toast#1]
I'm not sure if this is actually an issue with the bot or an issue with UH, but yesterday the bot seemed to go bananas reposting the same update:

![Screenshot](http://grahams.wtf/public/Screenshots/yRXVjl.png)

When it first started I imagined it was Adam over at UH fiddling with the page on the first alert day of the season, but then when it continued I ended up disabling the bot.  My apologies if this isn't the bot's fault. :)

**Comment by muerl** [comment]
👍 Happened to me as well.

**Comment by ErinMorelli** [comment]
Thanks for the heads up - looking into the issue now. Seems like it happened again today.

**Comment by cdevers** [comment]
Same thing happened today, too: 50+ instances of the same message. Had to turn it off on my employer’s Slack instance so as to not annoy my coworkers on Thanksgiving …

**Comment by ErinMorelli** [comment]
I just pushed out a new version of the app that re-worked the alert sending logic. In my testing it seems to have resolved the issue. We'll see for sure when the next status change happens. I'll leave this issue open until we have confirmation of the fix.

**Comment by grahams** [comment]
@ErinMorelli Great, I redeployed it to our slack instance and will let you know if it goes berzerk again.

**Comment by ErinMorelli** [comment]
Looks like UH updated the status today. I received just a single alert in my 2 slack channels. How did it work out for you @grahams ?

**Comment by grahams** [comment]
@ErinMorelli We also got a single alert in our slack!  Looks good!

**Comment by ErinMorelli** [comment]
Awesome! I'll close out this issue then. Let me know if you run into any more issues!
